### ISSUE TITLE
Expose an ability to have all the actions/cache calls to automagically be replaced with this

### ISSUE THREAD

**Issue by aaomidi** [runs-on/cache#23]
A potential technique is described here: https://gha-cache-server.falcondev.io/getting-started#_3-using-the-cache-server

This would transparently elevate the cache experience across the board.

**Comment by crohr** [comment]
Yes, on my todo-list!

**Comment by crohr** [comment]
The cache v2 is actually so much easier to support especially for S3 that I might wait until https://github.com/actions/cache/pull/1495 is merged and makes its way in most of the language-specific cache actions.
