### ISSUE TITLE
(Probably) Action reports cache not found when s3 credentials misconfigured

### ISSUE THREAD

**Issue by labeleddata** [runs-on/cache#25]
Hi, 
We're evaluating runs-on and experimenting with the cache. 
We think (based on evidence below) that:
When s3 is misconfigured and accessing gives a 403, the action repots that the key was not found, but it should error or report auth problems. 

> The cache action detected a local S3 bucket cache. Using it.
> Cache not found for input keys: /home/runner/_work/_tool/Python/3.10.14/x64-acfb00df7caf8b5650137b8f855e203b58ab4784bf6518061fc092eb576068e4
> 

Due to misconfiguration on our end, we know that the runner can't access that bucket . Trying it more directly gives a 403.

It did take a few hours to figure that out. A clearer error message here would be helpful for future users

**Comment by crohr** [comment]
Hi @labeleddata, if this is a config error, you should get a message starting with `Error listing objects with prefix` in the logs. Did you see this line?

**Comment by labeleddata** [comment]
Thanks. 
Oh I am not sure if it's in the logs, it's been many jobs since then. 
The ask here is a clearer and more explicit error message at the point of failiure. 
Niether "Error listing objects" or "cache not found" aren't telling me the root error. 

The reason we want explicit errors is that  we have a decently sized dev org, and all the engineers write GHA, sometimes. 

We want them all to use this, but don't want them all to become "runson" experts. Clear error messages means they can either solve it or know what/who to ask fast

**Comment by crohr** [comment]
Sure, it’s just that currently it’s supposed to be the message that gets spit out when there is a permission issue, and I don’t see it in the logs your shared so I’m wondering what was the root cause here. Also note that v2.6.3 now ships with a magic cache so that you don’t need to use this action anymore. https://runs-on.com/caching/magic-cache/

**Comment by labeleddata** [comment]
Closing this issue cause I don't remember the details and we got magic cache working
