### ISSUE TITLE
Support for MinIO

### ISSUE THREAD

**Issue by oprypkhantc** [runs-on/cache#3]
Hey!

Thank you for the awesome action. For some context, currently we're running a fork of an old action that uses MinIO SDK under the hood to download/upload cache from/to MinIO and S3, depending on which runners pick the job. It does the job fine, but isn't a drop-in replacement for `actions/cache` and doesn't support all of the options.

We'd like to migrate to this action instead. I understand that this isn't just a community action, but still :) Currently there's no documented way to specify a custom endpoint for this action to use a S3-compatible storage instead of AWS itself. It was mentioned on [Reddit](https://www.reddit.com/r/devops/comments/1argwgd/using_an_s3_bucket_as_a_github_actions_cache/
) that a custom endpoint *could* be specified through AWS credentials.

It kind of works, but is broken for configurations where path-style bucket naming is used (e.g. `https://minio/bucket-name` instead of `https://bucket-name.minio`), and there's no way to force path style through environment variables or config credentials file. This is why some other actions provide this option as an input: https://github.com/whywaita/actions-cache-s3/blob/main/action.yml#L51

In the case of runs-on, it could be provided as another environment variable, like `RUNS_ON_FORCE_PATH_STYLE` or `AWS_S3_FORCE_PATH_STYLE`. All that would be needed is another line when creating an AWS S3 client instance :)

Would you accept a PR with this change?

**Comment by oprypkhantc** [comment]
Well anyways I created a PR here: https://github.com/runs-on/cache/pull/4/files

I intentionally omitted the build files so you can do it yourself and be sure of them :)

**Comment by crohr** [comment]
@oprypkhantc sorry for not replying earlier, it looks like I somehow miss notifications fro this repo. Will have a proper look a bit later but looks fine to me, thanks!

**Comment by oprypkhantc** [comment]
Awesome :)

**Comment by crohr** [comment]
Should be available in latest `v4`

**Comment by oprypkhantc** [comment]
Thank you @crohr!
